/*
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * API version: 3.0
 * Contact: support@aylien.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package newsapi
import (
	"time"
)
// RepresentativeStory struct for RepresentativeStory
type RepresentativeStory struct {
	// ID of the story which is a unique identification
	Id int64 `json:"id,omitempty"`
	// The story permalink URL
	Permalink string `json:"permalink,omitempty"`
	// Published date of the story
	PublishedAt time.Time `json:"published_at,omitempty"`
	// Title of the story
	Title string `json:"title,omitempty"`
}
