/*
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * API version: 3.0
 * Contact: support@aylien.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package newsapi
// ShareCounts struct for ShareCounts
type ShareCounts struct {
	// Facebook shares count
	Facebook []ShareCount `json:"facebook,omitempty"`
	// Google Plus shares count
	GooglePlus []ShareCount `json:"google_plus,omitempty"`
	// LinkedIn shares count
	Linkedin []ShareCount `json:"linkedin,omitempty"`
	// Reddit shares count
	Reddit []ShareCount `json:"reddit,omitempty"`
}
