/*
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * API version: 3.0
 * Contact: support@aylien.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package newsapi
// ScopeLevel The scope by level
type ScopeLevel string

// List of ScopeLevel
const (
	INTERNATIONAL ScopeLevel = "international"
	NATIONAL ScopeLevel = "national"
	LOCAL ScopeLevel = "local"
)
