/*
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * API version: 3.0
 * Contact: support@aylien.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package newsapi
// Autocompletes struct for Autocompletes
type Autocompletes struct {
	// An array of autocompletes
	Autocompletes []Autocomplete `json:"autocompletes,omitempty"`
}
