/*
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * API version: 3.0
 * Contact: support@aylien.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package newsapi
// Source struct for Source
type Source struct {
	// A general explanation about the source
	Description string `json:"description,omitempty"`
	// The domain name of the source which is extracted from the source URL
	Domain string `json:"domain,omitempty"`
	// The home page URL of the source
	HomePageUrl string `json:"home_page_url,omitempty"`
	// The source id which is a unique value
	Id int32 `json:"id,omitempty"`
	// The number of websites that link to the source
	LinksInCount int32 `json:"links_in_count,omitempty"`
	// The source locations which are tend to be the physical locations of the source, e.g. BBC headquarter is located in London. 
	Locations []Location `json:"locations,omitempty"`
	// A URL which points to the source logo
	LogoUrl string `json:"logo_url,omitempty"`
	// The source name
	Name string `json:"name,omitempty"`
	Rankings Rankings `json:"rankings,omitempty"`
	// The source scopes which is tend to be scope locations of the source, e.g. BBC scopes is international. 
	Scopes []Scope `json:"scopes,omitempty"`
	// The title of the home page URL
	Title string `json:"title,omitempty"`
}
