/*
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * API version: 3.0
 * Contact: support@aylien.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package newsapi
// DeprecatedEntity struct for DeprecatedEntity
type DeprecatedEntity struct {
	// The unique ID of the entity
	Id string `json:"id,omitempty"`
	// The indices of the entity text
	Indices [][]int32 `json:"indices,omitempty"`
	Links EntityLinks `json:"links,omitempty"`
	// Describes how relevant an entity is to the article
	ProminenceScore float32 `json:"prominence_score,omitempty"`
	Sentiment EntitySentiment `json:"sentiment,omitempty"`
	// The stock_ticker of the entity (might be null)
	StockTicker string `json:"stock_ticker,omitempty"`
	SurfaceForms []DeprecatedEntitySurfaceForm `json:"surface_forms,omitempty"`
	// The entity text
	Text string `json:"text,omitempty"`
	// An array of the entity types
	Types []string `json:"types,omitempty"`
}
