/*
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * API version: 3.0
 * Contact: support@aylien.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package newsapi
// MediaFormat The format of media
type MediaFormat string

// List of MediaFormat
const (
	BMP MediaFormat = "BMP"
	GIF MediaFormat = "GIF"
	JPEG MediaFormat = "JPEG"
	PNG MediaFormat = "PNG"
	TIFF MediaFormat = "TIFF"
	PSD MediaFormat = "PSD"
	ICO MediaFormat = "ICO"
	CUR MediaFormat = "CUR"
	WEBP MediaFormat = "WEBP"
	SVG MediaFormat = "SVG"
)
