/**
 * AYLIEN News API
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@aylien.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CategoryLinks from './CategoryLinks';

/**
 * The Category model module.
 * @module model/Category
 * @version 2.0.0
 */
class Category {
    /**
     * Constructs a new <code>Category</code>.
     * @alias module:model/Category
     */
    constructor() { 
        
        Category.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Category</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Category} obj Optional instance to populate.
     * @return {module:model/Category} The populated <code>Category</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Category();

            if (data.hasOwnProperty('confident')) {
                obj['confident'] = ApiClient.convertToType(data['confident'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'Number');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = CategoryLinks.constructFromObject(data['links']);
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('taxonomy')) {
                obj['taxonomy'] = ApiClient.convertToType(data['taxonomy'], 'String');
            }
        }
        return obj;
    }


}

/**
 * It defines whether the extracted category is confident or not
 * @member {Boolean} confident
 */
Category.prototype['confident'] = undefined;

/**
 * The ID of the category
 * @member {String} id
 */
Category.prototype['id'] = undefined;

/**
 * The level of the category
 * @member {Number} level
 */
Category.prototype['level'] = undefined;

/**
 * @member {module:model/CategoryLinks} links
 */
Category.prototype['links'] = undefined;

/**
 * The score of the category
 * @member {Number} score
 */
Category.prototype['score'] = undefined;

/**
 * The taxonomy of the category
 * @member {module:model/Category.TaxonomyEnum} taxonomy
 */
Category.prototype['taxonomy'] = undefined;





/**
 * Allowed values for the <code>taxonomy</code> property.
 * @enum {String}
 * @readonly
 */
Category['TaxonomyEnum'] = {

    /**
     * value: "iab-qag"
     * @const
     */
    "iab-qag": "iab-qag",

    /**
     * value: "iptc-subjectcode"
     * @const
     */
    "iptc-subjectcode": "iptc-subjectcode"
};



export default Category;

