/**
 * AYLIEN News API
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Story from './Story';

/**
 * The Coverages model module.
 * @module model/Coverages
 * @version 3.0.0
 */
class Coverages {
    /**
     * Constructs a new <code>Coverages</code>.
     * @alias module:model/Coverages
     */
    constructor() { 
        
        Coverages.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Coverages</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Coverages} obj Optional instance to populate.
     * @return {module:model/Coverages} The populated <code>Coverages</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Coverages();

            if (data.hasOwnProperty('coverages')) {
                obj['coverages'] = ApiClient.convertToType(data['coverages'], [Story]);
            }
            if (data.hasOwnProperty('story_body')) {
                obj['story_body'] = ApiClient.convertToType(data['story_body'], 'String');
            }
            if (data.hasOwnProperty('story_language')) {
                obj['story_language'] = ApiClient.convertToType(data['story_language'], 'String');
            }
            if (data.hasOwnProperty('story_published_at')) {
                obj['story_published_at'] = ApiClient.convertToType(data['story_published_at'], 'Date');
            }
            if (data.hasOwnProperty('story_title')) {
                obj['story_title'] = ApiClient.convertToType(data['story_title'], 'String');
            }
        }
        return obj;
    }


}

/**
 * An array of coverages for the input story
 * @member {Array.<module:model/Story>} coverages
 */
Coverages.prototype['coverages'] = undefined;

/**
 * The input story body
 * @member {String} story_body
 */
Coverages.prototype['story_body'] = undefined;

/**
 * The input story language
 * @member {String} story_language
 */
Coverages.prototype['story_language'] = undefined;

/**
 * The input story published date
 * @member {Date} story_published_at
 */
Coverages.prototype['story_published_at'] = undefined;

/**
 * The input story title
 * @member {String} story_title
 */
Coverages.prototype['story_title'] = undefined;






export default Coverages;

