/**
 * AYLIEN News API
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeprecatedStory from './DeprecatedStory';

/**
 * The DeprecatedRelatedStories model module.
 * @module model/DeprecatedRelatedStories
 * @version 4.5.0
 */
class DeprecatedRelatedStories {
    /**
     * Constructs a new <code>DeprecatedRelatedStories</code>.
     * Story with deprecated entities
     * @alias module:model/DeprecatedRelatedStories
     */
    constructor() { 
        
        DeprecatedRelatedStories.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeprecatedRelatedStories</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeprecatedRelatedStories} obj Optional instance to populate.
     * @return {module:model/DeprecatedRelatedStories} The populated <code>DeprecatedRelatedStories</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeprecatedRelatedStories();

            if (data.hasOwnProperty('published_at.end')) {
                obj['published_at.end'] = ApiClient.convertToType(data['published_at.end'], 'Date');

                if ('published_at.end' !== 'publishedAtEnd') {
                  Object.defineProperty(obj, 'publishedAtEnd', {
                    get() {
                      return obj['published_at.end'];
                    }
                  });
                }
            }
            if (data.hasOwnProperty('published_at.start')) {
                obj['published_at.start'] = ApiClient.convertToType(data['published_at.start'], 'Date');

                if ('published_at.start' !== 'publishedAtStart') {
                  Object.defineProperty(obj, 'publishedAtStart', {
                    get() {
                      return obj['published_at.start'];
                    }
                  });
                }
            }
            if (data.hasOwnProperty('related_stories')) {
                obj['related_stories'] = ApiClient.convertToType(data['related_stories'], [DeprecatedStory]);

                if ('related_stories' !== 'relatedStories') {
                  Object.defineProperty(obj, 'relatedStories', {
                    get() {
                      return obj['related_stories'];
                    }
                  });
                }
            }
            if (data.hasOwnProperty('story_body')) {
                obj['story_body'] = ApiClient.convertToType(data['story_body'], 'String');

                if ('story_body' !== 'storyBody') {
                  Object.defineProperty(obj, 'storyBody', {
                    get() {
                      return obj['story_body'];
                    }
                  });
                }
            }
            if (data.hasOwnProperty('story_language')) {
                obj['story_language'] = ApiClient.convertToType(data['story_language'], 'String');

                if ('story_language' !== 'storyLanguage') {
                  Object.defineProperty(obj, 'storyLanguage', {
                    get() {
                      return obj['story_language'];
                    }
                  });
                }
            }
            if (data.hasOwnProperty('story_title')) {
                obj['story_title'] = ApiClient.convertToType(data['story_title'], 'String');

                if ('story_title' !== 'storyTitle') {
                  Object.defineProperty(obj, 'storyTitle', {
                    get() {
                      return obj['story_title'];
                    }
                  });
                }
            }
        }
        return obj;
    }


}

/**
 * The end of a period in which searched stories were published
 * @member {Date} published_at.end
 */
DeprecatedRelatedStories.prototype['published_at.end'] = undefined;

/**
 * The start of a period in which searched stories were published
 * @member {Date} published_at.start
 */
DeprecatedRelatedStories.prototype['published_at.start'] = undefined;

/**
 * An array of related stories for the input story
 * @member {Array.<module:model/DeprecatedStory>} related_stories
 */
DeprecatedRelatedStories.prototype['related_stories'] = undefined;

/**
 * The input story body
 * @member {String} story_body
 */
DeprecatedRelatedStories.prototype['story_body'] = undefined;

/**
 * The input story language
 * @member {String} story_language
 */
DeprecatedRelatedStories.prototype['story_language'] = undefined;

/**
 * The input story title
 * @member {String} story_title
 */
DeprecatedRelatedStories.prototype['story_title'] = undefined;






export default DeprecatedRelatedStories;

