/**
 * AYLIEN News API
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SentimentPolarity from './SentimentPolarity';

/**
 * The EntitySentiment model module.
 * @module model/EntitySentiment
 * @version 4.5.0
 */
class EntitySentiment {
    /**
     * Constructs a new <code>EntitySentiment</code>.
     * @alias module:model/EntitySentiment
     */
    constructor() { 
        
        EntitySentiment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntitySentiment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntitySentiment} obj Optional instance to populate.
     * @return {module:model/EntitySentiment} The populated <code>EntitySentiment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntitySentiment();

            if (data.hasOwnProperty('confidence')) {
                obj['confidence'] = ApiClient.convertToType(data['confidence'], 'Number');

                if ('confidence' !== 'confidence') {
                  Object.defineProperty(obj, 'confidence', {
                    get() {
                      return obj['confidence'];
                    }
                  });
                }
            }
            if (data.hasOwnProperty('polarity')) {
                obj['polarity'] = SentimentPolarity.constructFromObject(data['polarity']);

                if ('polarity' !== 'polarity') {
                  Object.defineProperty(obj, 'polarity', {
                    get() {
                      return obj['polarity'];
                    }
                  });
                }
            }
        }
        return obj;
    }


}

/**
 * Polarity confidence of the sentiment
 * @member {Number} confidence
 */
EntitySentiment.prototype['confidence'] = undefined;

/**
 * @member {module:model/SentimentPolarity} polarity
 */
EntitySentiment.prototype['polarity'] = undefined;






export default EntitySentiment;

