/**
 * AYLIEN News API
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@aylien.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Media model module.
 * @module model/Media
 * @version 2.0.0
 */
class Media {
    /**
     * Constructs a new <code>Media</code>.
     * @alias module:model/Media
     */
    constructor() { 
        
        Media.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Media</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Media} obj Optional instance to populate.
     * @return {module:model/Media} The populated <code>Media</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Media();

            if (data.hasOwnProperty('content_length')) {
                obj['content_length'] = ApiClient.convertToType(data['content_length'], 'Number');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The content length of media
 * @member {Number} content_length
 */
Media.prototype['content_length'] = undefined;

/**
 * The format of media
 * @member {module:model/Media.FormatEnum} format
 */
Media.prototype['format'] = undefined;

/**
 * The height of media
 * @member {Number} height
 */
Media.prototype['height'] = undefined;

/**
 * The type of media
 * @member {module:model/Media.TypeEnum} type
 */
Media.prototype['type'] = undefined;

/**
 * A URL which points to the media file
 * @member {String} url
 */
Media.prototype['url'] = undefined;

/**
 * The width of media
 * @member {Number} width
 */
Media.prototype['width'] = undefined;





/**
 * Allowed values for the <code>format</code> property.
 * @enum {String}
 * @readonly
 */
Media['FormatEnum'] = {

    /**
     * value: "BMP"
     * @const
     */
    "BMP": "BMP",

    /**
     * value: "GIF"
     * @const
     */
    "GIF": "GIF",

    /**
     * value: "JPEG"
     * @const
     */
    "JPEG": "JPEG",

    /**
     * value: "PNG"
     * @const
     */
    "PNG": "PNG",

    /**
     * value: "TIFF"
     * @const
     */
    "TIFF": "TIFF",

    /**
     * value: "PSD"
     * @const
     */
    "PSD": "PSD",

    /**
     * value: "ICO"
     * @const
     */
    "ICO": "ICO",

    /**
     * value: "CUR"
     * @const
     */
    "CUR": "CUR",

    /**
     * value: "WEBP"
     * @const
     */
    "WEBP": "WEBP",

    /**
     * value: "SVG"
     * @const
     */
    "SVG": "SVG"
};


/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Media['TypeEnum'] = {

    /**
     * value: "image"
     * @const
     */
    "image": "image",

    /**
     * value: "video"
     * @const
     */
    "video": "video"
};



export default Media;

