/**
 * AYLIEN News API
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client. 
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AylienNewsApi);
  }
}(this, function(expect, AylienNewsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AylienNewsApi.OneOfStoriesDeprecatedStories();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OneOfStoriesDeprecatedStories', function() {
    it('should create an instance of OneOfStoriesDeprecatedStories', function() {
      // uncomment below and update the code to test OneOfStoriesDeprecatedStories
      //var instane = new AylienNewsApi.OneOfStoriesDeprecatedStories();
      //expect(instance).to.be.a(AylienNewsApi.OneOfStoriesDeprecatedStories);
    });

    it('should have the property nextPageCursor (base name: "next_page_cursor")', function() {
      // uncomment below and update the code to test the property nextPageCursor
      //var instance = new AylienNewsApi.OneOfStoriesDeprecatedStories();
      //expect(instance).to.be();
    });

    it('should have the property publishedAtEnd (base name: "published_at.end")', function() {
      // uncomment below and update the code to test the property publishedAtEnd
      //var instance = new AylienNewsApi.OneOfStoriesDeprecatedStories();
      //expect(instance).to.be();
    });

    it('should have the property publishedAtStart (base name: "published_at.start")', function() {
      // uncomment below and update the code to test the property publishedAtStart
      //var instance = new AylienNewsApi.OneOfStoriesDeprecatedStories();
      //expect(instance).to.be();
    });

    it('should have the property stories (base name: "stories")', function() {
      // uncomment below and update the code to test the property stories
      //var instance = new AylienNewsApi.OneOfStoriesDeprecatedStories();
      //expect(instance).to.be();
    });

    it('should have the property warnings (base name: "warnings")', function() {
      // uncomment below and update the code to test the property warnings
      //var instance = new AylienNewsApi.OneOfStoriesDeprecatedStories();
      //expect(instance).to.be();
    });

  });

}));
